version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=https://bookshop-api-er7t.onrender.com
    container_name: bookshop_client